apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: gate
  name: spin-gate-nodeport-service
  namespace: spinnaker
spec:
  ports:
  - name: http
    port: 8084
    protocol: TCP
    targetPort: 8084
  
  selector:
    app: spin
    cluster: spin-gate
  type: NodePort

