apiVersion: v1
kind: Service
metadata:
  name: helloagain-uat
  namespace: apps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-helloagain-uat: "true"
  sessionAffinity: None
  type: LoadBalancer
